export const getContinents = () => {
  return {
    NorthAmerica: [
      "alaska",
      "alberta",
      "central-america",
      "eastern-us",
      "greenland",
      "northwest-territory",
      "ontario",
      "quebec",
      "western-us",
    ],
    SouthAmerica: ["argentina", "brazil", "peru", "venezuela"],
    Europe: [
      "great-britain",
      "iceland",
      "northern-europe",
      "scandinavia",
      "southern-europe",
      "ukraine",
      "western-europe",
    ],
    Africa: [
      "congo",
      "east-africa",
      "egypt",
      "madagascar",
      "north-africa",
      "south-africa",
    ],
    Asia: [
      "afghanistan",
      "china",
      "india",
      "irkutsk",
      "japan",
      "kamchatka",
      "middle-east",
      "mongolia",
      "siam",
      "siberia",
      "ural",
      "yakutsk",
    ],
    Australia: [
      "eastern-australia",
      "indonesia",
      "new-guinea",
      "western-australia",
    ],
  };
};
