import { Continent } from "../types/gameTypes.ts";

export const getContinents = (): Continent => {
  return {
    NorthAmerica: [
      "alaska",
      "alberta",
      "central-america",
      "eastern-us",
      "greenland",
      "northwest-territory",
      "ontario",
      "quebec",
      "western-us",
    ],
    SouthAmerica: ["argentina", "brazil", "peru", "venezuela"],
    Europe: [
      "great-britain",
      "iceland",
      "northern-europe",
      "scandinavia",
      "southern-europe",
      "ukraine",
      "western-europe",
    ],
    Africa: [
      "congo",
      "east-africa",
      "egypt",
      "madagascar",
      "north-africa",
      "south-africa",
    ],
    Asia: [
      "afghanistan",
      "china",
      "india",
      "irkutsk",
      "japan",
      "kamchatka",
      "middle-east",
      "mongolia",
      "siam",
      "siberia",
      "ural",
      "yakutsk",
    ],
    Australia: [
      "eastern-australia",
      "indonesia",
      "new-guinea",
      "western-australia",
    ],
  };
};

export const neighbouringTerritories = (): Continent => {
  return {
    alaska: ["northwest-territory", "alberta", "kamchatka"],
    "northwest-territory": ["alaska", "greenland", "alberta", "ontario"],
    greenland: ["northwest-territory", "ontario", "quebec", "iceland"],
    alberta: ["alaska", "northwest-territory", "ontario", "western-us"],
    ontario: [
      "northwest-territory",
      "greenland",
      "quebec",
      "alberta",
      "western-us",
      "eastern-us",
    ],
    quebec: ["greenland", "ontario", "eastern-us"],
    "western-us": ["alberta", "ontario", "eastern-us", "central-america"],
    "eastern-us": ["ontario", "quebec", "western-us", "central-america"],
    "central-america": ["western-us", "eastern-us", "venezuela"],
    venezuela: ["central-america", "brazil", "peru"],
    peru: ["venezuela", "brazil", "argentina"],
    brazil: ["venezuela", "peru", "argentina", "north-africa"],
    argentina: ["peru", "brazil"],
    iceland: ["greenland", "great-britain", "scandinavia"],
    scandinavia: ["iceland", "ukraine", "northern-europe", "great-britain"],
    ukraine: [
      "scandinavia",
      "northern-europe",
      "southern-europe",
      "ural",
      "afghanistan",
      "middle-east",
    ],
    "great-britain": [
      "iceland",
      "scandinavia",
      "northern-europe",
      "western-europe",
    ],
    "northern-europe": [
      "great-britain",
      "scandinavia",
      "ukraine",
      "southern-europe",
      "western-europe",
    ],
    "western-europe": [
      "great-britain",
      "northern-europe",
      "southern-europe",
      "north-africa",
    ],
    "southern-europe": [
      "western-europe",
      "northern-europe",
      "ukraine",
      "middle-east",
      "egypt",
      "north-africa",
    ],
    "north-africa": [
      "western-europe",
      "southern-europe",
      "egypt",
      "east-africa",
      "congo",
      "brazil",
    ],
    egypt: ["southern-europe", "middle-east", "east-africa", "north-africa"],
    "east-africa": [
      "egypt",
      "middle-east",
      "madagascar",
      "south-africa",
      "congo",
      "north-africa",
    ],
    congo: ["north-africa", "east-africa", "south-africa"],
    "south-africa": ["congo", "east-africa", "madagascar"],
    madagascar: ["south-africa", "east-africa"],
    ural: ["ukraine", "siberia", "china", "afghanistan"],
    siberia: ["ural", "yakutsk", "irkutsk", "mongolia", "china"],
    yakutsk: ["siberia", "irkutsk", "kamchatka"],
    irkutsk: ["siberia", "yakutsk", "kamchatka", "mongolia"],
    kamchatka: ["irkutsk", "yakutsk", "alaska", "japan", "mongolia"],
    mongolia: ["irkutsk", "kamchatka", "china", "siberia"],
    china: ["mongolia", "siberia", "ural", "afghanistan", "india", "siam"],
    afghanistan: ["ukraine", "ural", "china", "india", "middle-east"],
    "middle-east": [
      "ukraine",
      "afghanistan",
      "india",
      "east-africa",
      "egypt",
      "southern-europe",
    ],
    india: ["afghanistan", "china", "siam", "middle-east"],
    siam: ["india", "china", "indonesia"],
    japan: ["kamchatka", "mongolia"],
    indonesia: ["siam", "new-guinea", "western-australia"],
    "new-guinea": ["indonesia", "eastern-australia", "western-australia"],
    "western-australia": ["indonesia", "new-guinea", "eastern-australia"],
    "eastern-australia": ["new-guinea", "western-australia"],
  };
};
